### ISSUE TITLE
Water sounds like a toilet flushing

### ISSUE THREAD

**Issue by UltraBlackLinux** [abbydiode/half-mine#2]
Why is it like that - Please change that

**Comment by abigailwillow** [comment]
I assume you mean the swimming sounds? It sounds like that because those are the swimming sounds used in Half-Life. The sounds that are used are `pl_swim1.wav`, `pl_swim2.wav`, `pl_swim3.wav`, and `pl_swim4.wav` from `Half-Life/valve/sound/player/`

**Comment by UltraBlackLinux** [comment]
Yeah these. Is minecraft doing some weird pitching then? I don't think they sounded that out of place in HL2

**Comment by abigailwillow** [comment]
Minecraft indeed applies random pitch to a lot of sounds which is unfortunately beyond my control. I remove the random pitch whenever I can but not all sounds allow me to do that.
